<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();

$piece_packing = 1;
if ( $product->getCustomAttribute('pieces_in_the_package')->getValue() == 0 || $product->getCustomAttribute('pieces_in_the_package')== null ||  $product->getCustomAttribute('pieces_in_the_package')->getValue() == '') {
    $piece_packing = 1;
}else{
    $piece_packing = $product->getCustomAttribute('pieces_in_the_package')->getValue()*1;
}
?>
<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()) : ?>
            <div class="field qty">
                <label class="label" for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control qty-wrapper">
                    <a href="javascript:void(0);" class="product_view_qty_btn decrement_btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="2" viewBox="0 0 10 2" fill="none">
                            <rect width="10" height="2" fill="#878787"/>
                        </svg>
                    </a>

                    <input type="number"
                           data-role="qty"
                           id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                           class="input-text qty back "
                           data-validate="{'required-number':true,'validate-greater-than-zero':true, 'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
                           name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                           value="1"
						   data-multiplicity="1"
						   <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>
                           readonly="readonly"
                    />
                    <a href="javascript:void(0);" class="product_view_qty_btn increment_btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10" fill="none">
                            <rect y="4" width="10" height="2" fill="#393939"/>
                            <rect x="4" y="10" width="10" height="2" transform="rotate(-90 4 10)" fill="#393939"/>
                        </svg>
                    </a>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable()) : ?>
            <div class="product-item-actions">
                <div class="actions-primary">
                    <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                </div>
            </div>
        <?php else : ?>
            <?php if ($product->getIsSalable()) : ?>
                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else : ?>
                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
</div>


