<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
<div class="product_sku">
    <span class="title-sku">
        <?= /* @escapeNotVerified */ __('Sku:') ?>
    </span>
    <span class="sku">
        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($product, $product->getSku(), 'sku'); ?>
    </span>
</div>