<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><strong><?= $block->escapeHtml(__('Registration is free and easy!')) ?></strong></p>
            <ul>
                <li><?= $block->escapeHtml(__('Faster order')) ?></li>
                <li><?= $block->escapeHtml(__('Save multiple shipping addresses')) ?></li>
                <li><?= $block->escapeHtml(__('View and track your order and more.')) ?></li>
            </ul>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>