<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<?php
//$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();

if (null !== $product->getCustomAttribute('pieces_in_the_package')) {
    $piece_packing = $product->getCustomAttribute('pieces_in_the_package')->getValue()*1;
}else{
    $piece_packing = 1;
}

if (null !== $product->getCustomAttribute('weight')) {
    $weight_packing = $product->getCustomAttribute('weight')->getValue()*1;
}else{
    $weight_packing = 1;
}



$price_piece_packing = $product->getPrice()*1;
$price_piece_packing_final = $product->getFinalPrice()*1;

$price_package=  floor($price_piece_packing*$piece_packing * 100) / 100;
$price_package_final =  floor($price_piece_packing_final*$piece_packing * 100) / 100;
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <div class="image-Wrapper">
            <?php if ($block->hasProductUrl()) :?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
            </a>
        <?php else :?>
            </span>
        <?php endif; ?>
        </div>

        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <div class="product_sku">
                <span class="label">  <?= /* @escapeNotVerified */ __('SKU') ?></span>
                <span class="value"><?php echo $_item->getSku() ?></span>
            </div>


            <div class="prices-wrapper">
                <div class="piece_packing hidden">
                    <span class="label">  <?= /* @escapeNotVerified */ __('Piece packing') ?></span>
                    <span class="value"><?php echo $piece_packing ; ?></span>
                </div>
                <div class="price_piece_packing mobile">
                    <span class="label">  <?= /* @escapeNotVerified */ __('Price piece packing') ?></span>
                    <?php if ($price_package >  $price_package_final) { ?>
                        <span class="value">
                                          <?php echo number_format($price_piece_packing_final, 2, ',', ''); ?>
                                        </span>
                        <span class="value old">
                                            <?php echo number_format($price_piece_packing, 2, ',', ''); ?>
                                        </span>
                    <?php } else{?>
                        <span class="value">
                                           <?php echo number_format($price_piece_packing, 2, ',', ''); ?>
                                        </span>
                    <?php } ?>

                </div>
                <div class="price_package mobile hidden">
                    <span class="label"><?= /* @escapeNotVerified */ __('Price package'); ?></span>
                    <?php if ($price_package >  $price_package_final) { ?>
                        <span class="value">
                                           <?php echo number_format($price_package_final, 2, ',', ''); ?>
                                        </span>
                        <span class="value old">
                                          <?php echo number_format($price_package, 2, ',', ''); ?>
                                        </span>
                    <?php } else{?>
                        <span class="value">
                                          <?php echo number_format($price_package, 2, ',', ''); ?>
                                        </span>
                    <?php } ?>
                </div>
            </div>
            <div class="subtotal_wrapper mobile">
                <?php if ($canApplyMsrp) :?>
                    <span class="label"><?= $block->escapeHtml(__('Sum')) ?></span>
                    <span class="cart msrp subtotal value">--</span>
                <?php else :?>
                    <span class="label"><?= $block->escapeHtml(__('Sum')) ?></span>
                    <span class="cart msrp subtotal value"> <?= $block->getRowTotalHtml($_item) ?></span>
                <?php endif; ?>
            </div>
            <?php if ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) :?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                            <?php else :?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <td class="col weight hidden" data-th="<?= $block->escapeHtml(__('Total weight, kg')) ?>">
        <?php echo $weight_packing ; ?>
    </td>
    <td class="col price_piece_packing" data-th="<?= $block->escapeHtml(__('Price piece packing')) ?>">
        <?php echo number_format($price_piece_packing, 2, ',', ''); ?>
    </td>

    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>

                    <div class="control qty-wrapper">
                        <button type="submit"
                                name="update_cart_action"
                                data-cart-item-update=""
                                value="update_qty"
                                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                                class="action update product_view_qty_btn decrement_btn"
                               >
                            <svg xmlns="http://www.w3.org/2000/svg" width="10" height="2" viewBox="0 0 10 2" fill="none">
                                <rect width="10" height="2" fill="#878787"/>
                            </svg>
                        </button>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
							   data-multiplicity="1"
                               type="number"
                               size="4"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"
                               readonly/>
                        <button type="submit"
                                name="update_cart_action"
                                data-cart-item-update=""
                                value="update_qty"
                                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                                class="action update product_view_qty_btn increment_btn"

                                >
                            <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10" fill="none">
                                <rect y="4" width="10" height="2" fill="#393939"/>
                                <rect x="4" y="10" width="10" height="2" transform="rotate(-90 4 10)" fill="#393939"/>
                            </svg>
                        </button>
                    </div>
                </label>

            </div>
        </div>
    </td>
    <td class="col qty hidden" data-th="<?= $block->escapeHtml(__('Qty piece')) ?>">
        <?php echo $block->escapeHtmlAttr($block->getQty()); ?>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Sum')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>

</tbody>

