<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
//$this->getLayout->createBlock("Magento\Cms\Block\Block")->setBlockId("")->toHtml();
//$block->getChildHtml()
//
?>

<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$logo_template =  'Magento_Theme::html/footer/logo_'.$storeManager->getStore()->getCode().'.phtml';

$store = $storeManager->getStore();
?>
<div class="footer-container">
    <div class="footer-top">
        <div class="footer_logo_container">
            <a class="footer_logo" href="<?php echo $store->getUrl() ?>">
                <?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate($logo_template)->toHtml(); ?>
            </a>
        </div>
        <div class="subscribe_to_news_wrapper">
            <div class="title"><?php echo __('Find out first about promotions, discounts and news') ?></div>
            <?= $this->getChildHtml() ?>
        </div>
    </div>
    <div class="footer-bottom footer_menus">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("footer_menus")->toHtml(); ?>
    </div>
</div>
<div class="copyright-wrapper">
    <div class="copyright-container">
        <address><?= /* @escapeNotVerified */ $this->getCopyright() ?></address>
        <div class="create-at">
            <span class="desktop"> <?php echo __('Website developed by web studio') ?></span>
            <span class="mobile"> <?php echo __('Site development') ?></span>
            <a href="https://studio-creative.com.ua/" target="_blank">"Creative"</a>
        </div>
    </div>
</div>






