<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
$productId = $block->getProduct()->getId();
?>
<div class="swatch-opt-container">
<div class="swatch-opt-<?= /* @escapeNotVerified */ $productId ?>"
     data-role="swatch-option-<?= /* @escapeNotVerified */ $productId ?>"></div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= /* @escapeNotVerified */ $productId ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?= /* @escapeNotVerified */ $block->getNumberSwatchesPerProduct(); ?>,
                "jsonConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?= /* @escapeNotVerified */ $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= /* @escapeNotVerified */ $productId ?>]": {
            "priceBox": {
                "priceConfig": {
                    "priceFormat": <?= /* @escapeNotVerified */ $block->getPriceFormatJson(); ?>,
                    "prices": <?= /* @escapeNotVerified */ $block->getPricesJson(); ?>
                }
            }
        }
    }
</script>

<script type="text/javascript">
    require(['jquery','Magento_Swatches/js/swatch-renderer','owlcarousel'],function($,swatch){
        $(document).on('swatch.initialized', function() {
            $(".product-item .swatch-attribute-options").addClass('owl-carousel');
            $(".product-item .swatch-attribute-options.owl-carousel").owlCarousel({
                "items" : 4,
                loop:false,
                margin:0,
                nav: true,
                dots: false,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:2,
                        nav:true,
                        dots:false
                    },
                    450:{
                        items:2,
                        nav:true,
                        dots:false
                    },
                    771:{
                        items:3,
                        nav:true,
                        dots:false
                    },
                    900:{
                        items:3,
                        nav:true,
                        dots:false
                    },
                    1200:{
                        items:4,
                        nav:true,
                        dots:false
                    }
                },
            });
        });
    });
</script>