<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
	$_product = $block->getProduct();
	$product_type = $_product->getTypeId();
?>
<?php /* if($product_type == 'grouped'): ?>
	<?php
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
		$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
		$childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
		$priceForAll = 0;
		foreach ($childProductCollection as $child) {
			if($child->getQty() * 1 > 0) {
				$priceForAll += $child->getFinalPrice();
			}
		}
	?>
	<div class="price-box" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
		<p class="minimal-price">
			<span class="grouped-price-label"><?php echo $priceHelper->currency($priceForAll, true, false); ?></span>
		</p>
	</div>
<?php endif; */ ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
