<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= $block->escapeHtml(__('Shop By')) ?></strong>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                       class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php
            $filters = $block->getFilters();
            $active_filters_str = implode(' ', range(3, count($filters)-1));
            ?>
                <?php foreach ($filters as $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <?php if (!$wrapOptions): ?>
                            <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "<?php echo $active_filters_str ?>", "multipleCollapsible": true}}'>
                            <?php  $wrapOptions = true;
                        endif; ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>