<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 *
 * @var $block \Tigren\Ajaxlogin\Block\Messages\Forgot\Error
 */
?>
<div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-message-error">
    <div class="mb-login-container-login">
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <div class="mb-error-message">
                <h4 class="mb-message-error"><?php echo __('Failed to Send Email!'); ?></h4>
                <p class="message"><?php echo __('We received too many requests for password resets. Please wait and try again later.'); ?></p>
            </div>
        </div>
    </div>
</div>
