<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 *
 *
 * @var $block \Tigren\Ajaxlogin\Block\Messages\Forgot\Success
 */
?>

<div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-message-success">
    <div class="mb-login-container-login">
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <div class="mb-successful-message">
                <div class="mb-loading">
                    <h4 class="mb-message-successs"><?php echo __('Sent Email Successfully!'); ?></h4>
                    <p class="message"></p>
                </div>
            </div>
        </div>
    </div>
</div>
