<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$logo_template =  'Magento_Theme::html/header/logo_'.$storeManager->getStore()->getCode().'.phtml';
	$logo_mobile_template =  'Magento_Theme::html/header/logo_mobile_'.$storeManager->getStore()->getCode().'.phtml';
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate($logo_template)->toHtml(); ?>
		<div class="logo_mobile">
			<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate($logo_mobile_template)->toHtml(); ?>
		</div>
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>
