<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Tigren\Ajaxlogin\Block\Messages\Logout\Error
 */
?>
<div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-message-error">
    <div class="mb-login-container-login">
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <div class="mb-error-message">
                <p class="message"></p>
            </div>
        </div>
    </div>
</div>
