<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="contact_form_wrapper">
	<div class="contact_form_top_block">
		<div class="form_title">
			<span class="bg_text"><?php echo __('Contact us'); ?></span>
			<span class="main_text"><?php echo __('Contact us'); ?></span>
		</div>
		<div class="contact_form_links">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_page_links')->toHtml(); ?>
		</div>
	</div>
	<form class="form contact"
		  action="<?= $block->escapeUrl($block->getFormAction()) ?>"
		  id="contact-form"
		  method="post"
		  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
		  data-mage-init='{"validation":{}}'>
		<fieldset class="fieldset">
			<div class="fields_wrap">
				<div class="field name required">
					<div class="control">
						<input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?= $block->escapeHtmlAttr(__('First Name')) ?>*"/>
					</div>
				</div>
				<div class="field email required">
					<div class="control">
						<input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>*"/>
					</div>
				</div>
				<div class="field telephone">
					<div class="control">
						<input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Telephone')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" placeholder="<?= $block->escapeHtmlAttr(__('Telephone')) ?>"/>
					</div>
				</div>
				<div class="field comment required">
					<div class="control">
						<textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="<?= $block->escapeHtmlAttr(__('Comment')) ?>*" ><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
					</div>
				</div>
				<?= $block->getChildHtml('form.additional.info') ?>
			</div>
		</fieldset>
		<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value="" />
				<button type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit primary">
					<span><?= $block->escapeHtml(__('Send')) ?></span>
				</button>
			</div>
		</div>
	</form>
</div>