<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
//$this->getLayout->createBlock("Magento\Cms\Block\Block")->setBlockId("")->toHtml();
//$block->getChildHtml()
//
?>

<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$logo_template =  'Magento_Theme::html/footer/logo_'.$storeManager->getStore()->getCode().'.phtml';

$store = $storeManager->getStore();
?>
<div class="footer-container">
    <div class="footer-top">
        <div class="f_logo">
            <a class="footer_logo" href="<?php echo $store->getUrl() ?>">
                <?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate($logo_template)->toHtml(); ?>
            </a>
        </div>
        <div class="pnones-container">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("footer_phone")->toHtml(); ?>
        </div>
    </div>
    <div class="footer-bottom footer_menus">

        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("footer_menus")->toHtml(); ?>
        <div class="footer-menu">
            <div class="footer-menu_content">
                <div class="title"><?php echo __('Subscribe to news') ?></div>
                <?= $this->getChildHtml() ?>
                <div class="title"><?php echo __('We are on social networks') ?></div>
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("social-footer")->toHtml(); ?>
            </div>
        </div>


    </div>
</div>
<div class="copyright-wrapper">
    <div class="copyright-container">
        <address><?= /* @escapeNotVerified */ $this->getCopyright() ?></address>
        <div class="create-at"> <?php echo __('Website developed by web studio') ?> <a href="https://studio-creative.com.ua/" target="_blank">"Creative"</a> </div>
    </div>
</div>






