<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation">
    <div class="header-mobile-menu-wrepper mobile">
        <div class="mobile header-mobile-menu" >
            <div class="left">
                <div class="back-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="21" viewBox="0 0 24 21" fill="none">
                        <rect y="10" width="24" height="1" fill="#3069B3"/>
                        <rect x="0.707031" y="10.293" width="14.1421" height="1" transform="rotate(45 0.707031 10.293)" fill="#3069B3"/>
                        <rect y="10" width="14.1421" height="1" transform="rotate(-45 0 10)" fill="#3069B3"/>
                    </svg>
                </div>
                <div class="category-title">
                    <span></span>
                </div>
            </div>
            <div class="social-icons-mobile"></div>
        </div>
    </div>
    <ul>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
