<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$catid = $this->getCategory_id();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$category = $categoryFactory->create()->load($catid);
$_productCollection = $category->getProductCollection()->addAttributeToSelect('*')->addAttributeToFilter('status',1);
$_productCollection->getSelect()->order(new Zend_Db_Expr('RAND()'))->limit(5);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>
<?php if (!$_productCollection->count()): ?>
   
<?php else: ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	<div class="tab_products_list">
		<div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
			<ol class="products list items product-items owl-carousel">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
				<li class="item product product-item">
					<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
						<?php
						$productImage = $block->getImage($_product, $imageDisplayArea);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>
						<?php // Product Image ?>
						<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<?php if($category->getId() == 57): ?>
								<div class="product_cat_label novelity"><span><?php echo __('Novelty'); ?></span></div>
							<?php elseif($category->getId() == 58): ?>
								<div class="product_cat_label top_sales"><span><?php echo __('Top Selling'); ?></span></div>
							<?php elseif($category->getId() == 59): ?>
								<div class="product_cat_label action"><span><?php echo __('Action'); ?></span></div>
							<?php endif; ?>
							<?= $productImage->toHtml() ?>
						</a>
						<div class="product details product-item-details">
							<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
								</a>
							</strong>
							<?php if($_product->getTypeId() != 'grouped'): ?>
								<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
							<?php else: ?>
								<?php
									$childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
									$assicoateProductsQty = 0;
									$priceForAll = 0;
									foreach ($childProductCollection as $child) {
										if($child->getQty() * 1 > 0) {
											$priceForAll += $child->getFinalPrice();
										}
										$assicoateProductsQty += $child->getQty() * 1;
									}
								?>
								<?php if($assicoateProductsQty != 0): ?>
									<div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $_product->getId(); ?>" data-price-box="product-id-<?php echo $_product->getId(); ?>">
										<span class="price-container price-final_price tax weee">
											<span id="product-price-<?php echo $_product->getId(); ?>" data-price-amount="<?php echo $priceHelper->currency($priceForAll, true, false); ?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $priceHelper->currency($priceForAll, true, false); ?></span></span>
										</span>
									</div>
								<?php endif; ?>
							<?php endif; ?>
							<?= $block->getProductDetailsHtml($_product) ?>
							<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
							
							<?php $product_factory = $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?>
							
							<?php if($product_factory): ?>
								<div class="product_factory">
									<span class="label"><?php echo __('Factory:'); ?></span>
									<span class="value"><?php echo $product_factory; ?></span>
								</div>
							<?php endif; ?>
							
							<?php if($_product->getTypeId() == 'grouped'): ?>
								<?php if($assicoateProductsQty != 0): ?>
									<div class="product_consists">
										<span><?php echo __('Consists of %1 elements', $assicoateProductsQty); ?></span>
									</div>
								<?php endif; ?>
							<?php endif; ?>
							
							<div class="product-item-inner">
								<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
									<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
										<?php if ($_product->isSaleable()): ?>
											<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="action tocart primary">
												<span><?= /* @escapeNotVerified */ __('Buy') ?></span>
											</a>
											<?php /* $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $postParams['action'] ?>" method="post">
												<input type="hidden" name="product" value="<?php echo $postParams['data']['product'] ?>">
												<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
												<?= $block->getBlockHtml('formkey') ?>
												<button type="submit"
														title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
														class="action tocart primary">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											</form><?php  */ ?>
										<?php else: ?>
											<?php if ($_product->isAvailable()): ?>
												<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
										<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</li>
				<?php endforeach; ?>
			</ol>
		</div>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
