<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
$om = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="top_toolbar">
		<?= $block->getToolbarHtml() ?>
	</div>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$item_count = 0;
    ?>
	<?php if ($block->getMode() == 'grid'): ?>
		<div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
			<ol class="products list items product-items">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
							<?php
							$productImage = $block->getImage($_product, $imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?= $productImage->toHtml() ?>
							</a>
							<div class="product details product-item-details">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
										<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
									</a>
								</strong>
								
								<?php if($_product->getTypeId() != 'grouped'): ?>
									<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
								<?php else: ?>
									<?php
										$childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
										$assicoateProductsQty = 0;
										$priceForAll = 0;
										foreach ($childProductCollection as $child) {
											if($child->getQty() * 1 > 0) {
												$priceForAll += $child->getFinalPrice();
											}
											$assicoateProductsQty += $child->getQty() * 1;
										}
									?>
									<?php if($assicoateProductsQty != 0): ?>
										<div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $_product->getId(); ?>" data-price-box="product-id-<?php echo $_product->getId(); ?>">
											<span class="price-container price-final_price tax weee">
												<span id="product-price-<?php echo $_product->getId(); ?>" data-price-amount="<?php echo $priceHelper->currency($priceForAll, true, false); ?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $priceHelper->currency($priceForAll, true, false); ?></span></span>
											</span>
										</div>
									<?php endif; ?>
								<?php endif; ?>
								
								<?= $block->getProductDetailsHtml($_product) ?>
								
								<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
								
								<?php $product_factory = $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?>
								<?php if($product_factory): ?>
									<div class="product_factory">
										<span class="label"><?php echo __('Factory:'); ?></span>
										<span class="value"><?php echo $product_factory; ?></span>
									</div>
								<?php endif; ?>
								
								<?php if($_product->getTypeId() == 'grouped'): ?>
									<?php if($assicoateProductsQty != 0): ?>
										<div class="product_consists">
											<span><?php echo __('Consists of %1 elements', $assicoateProductsQty); ?></span>
										</div>
									<?php endif; ?>
								<?php else: ?>
									<?php
										$width = $_product->getResource()->getAttribute('width')->getFrontend()->getValue($_product);
										$height = $_product->getResource()->getAttribute('height')->getFrontend()->getValue($_product);
										$depth = $_product->getResource()->getAttribute('depth')->getFrontend()->getValue($_product);
										$length = $_product->getResource()->getAttribute('length')->getFrontend()->getValue($_product);
									?>
									<div class="product_dimensions">
										<?php if($width): ?>
											<span class="width"><?php echo number_format($width, 1, '.', ''); ?>см</span>
										<?php endif; ?>
										<?php if($height): ?>
											<span class="height"><?php echo number_format($height, 1, '.', ''); ?>см</span>
										<?php endif; ?>
										<?php if($depth): ?>
											<span class="depth"><?php echo number_format($depth, 1, '.', ''); ?>см</span>
										<?php endif; ?>
										<?php if($length): ?>
											<span class="length"><?php echo number_format($length, 1, '.', ''); ?>см</span>
										<?php endif; ?>
									</div>
								<?php endif; ?>

								<div class="product-item-inner">
									<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
										<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
											<?php if ($_product->isSaleable()): ?>
												<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="action tocart primary">
													<span><?= /* @escapeNotVerified */ __('Buy') ?></span>
												</a>
												<?php //$postParams = $block->getAddToCartPostParams($_product); ?>
												<?php /*  ?><form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?=  $postParams['action'] ?>" method="post">
													<input type="hidden" name="product" value="<?=  $postParams['data']['product'] ?>">
													<input type="hidden" name="<?=  Action::PARAM_NAME_URL_ENCODED ?>" value="<?=  $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
													<?= $block->getBlockHtml('formkey') ?>
													<button type="submit"
															title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
															class="action tocart primary">
														<span><?=  __('Add to Cart') ?></span>
													</button>
												</form><?php  */ ?>
											<?php else: ?>
												<?php if ($_product->isAvailable()): ?>
													<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
					<?php if($item_count == 3): ?>
						<li class="item product product-item">
							<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('catalog_text_block')->toHtml(); ?>
						</li>
					<?php endif; ?>
					<?php $item_count++; ?>
				<?php endforeach; ?>
			</ol>
		</div>
	<?php else: ?>
		<div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
			<?php $brandIds = []; ?>
			<ol class="products list items product-items">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
							<?php
							$productImage = $block->getImage($_product, $imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?= $productImage->toHtml() ?>
							</a>
							<div class="product details product-item-details">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<div class="left_column">
									<strong class="product name product-item-name">
										<a class="product-item-link"
										   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
											<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
										</a>
									</strong>
									<div class="dimensions_wrapper">
										<?php if($_product->getTypeId() != 'grouped'): ?>
											<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
										<?php else: ?>
											<?php
												$childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
												$assicoateProductsQty = 0;
												$priceForAll = 0;
												foreach ($childProductCollection as $child) {
													if($child->getQty() * 1 > 0) {
														$priceForAll += $child->getFinalPrice();
													}
													$assicoateProductsQty += $child->getQty() * 1;
												}
											?>
											<div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $_product->getId(); ?>" data-price-box="product-id-<?php echo $_product->getId(); ?>">
												<span class="price-container price-final_price tax weee">
													<span id="product-price-<?php echo $_product->getId(); ?>" data-price-amount="<?php echo $priceHelper->currency($priceForAll, true, false); ?>" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?php echo $priceHelper->currency($priceForAll, true, false); ?></span></span>
												</span>
											</div>
										<?php endif; ?>
										<?php
											$width = $_product->getResource()->getAttribute('width')->getFrontend()->getValue($_product);
											$height = $_product->getResource()->getAttribute('height')->getFrontend()->getValue($_product);
											$depth = $_product->getResource()->getAttribute('depth')->getFrontend()->getValue($_product);
											$length = $_product->getResource()->getAttribute('length')->getFrontend()->getValue($_product);
										?>
										<div class="product_dimensions">
											<?php if($width): ?>
												<span class="width"><?php echo number_format($width, 1, '.', ''); ?>см</span>
											<?php endif; ?>
											<?php if($height): ?>
												<span class="height"><?php echo number_format($height, 1, '.', ''); ?>см</span>
											<?php endif; ?>
											<?php if($depth): ?>
												<span class="depth"><?php echo number_format($depth, 1, '.', ''); ?>см</span>
											<?php endif; ?>
											<?php if($length): ?>
												<span class="length"><?php echo number_format($length, 1, '.', ''); ?>см</span>
											<?php endif; ?>
										</div>
									</div>
									<div class="attributes_list">
										<?php
											$product_factory = $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product);
											$folding = $_product->getResource()->getAttribute('folding')->getFrontend()->getValue($_product);
											$niche_clothes = $_product->getResource()->getAttribute('niche_clothes')->getFrontend()->getValue($_product);
											$furniture_material = $_product->getResource()->getAttribute('furniture_material')->getFrontend()->getValue($_product);
											$facade_color = $_product->getResource()->getAttribute('facade_color')->getFrontend()->getValue($_product);
										?>
										<div class="left_items">
											<?php if($product_factory): ?>
												<div class="attribute_item">
													<span class="label"><?php echo __('Factory:'); ?></span>
													<span class="value"><?php echo $product_factory; ?></span>
												</div>
											<?php endif; ?>
											<?php if($folding): ?>
												<div class="attribute_item">
													<span class="label"><?php echo __('Folding:'); ?></span>
													<span class="value"><?php echo $folding; ?></span>
												</div>
											<?php endif; ?>
											<?php if($niche_clothes): ?>
												<div class="attribute_item">
													<span class="label"><?php echo __('Niche for linen:'); ?></span>
													<span class="value"><?php echo $niche_clothes; ?></span>
												</div>
											<?php endif; ?>
										</div>
										<div class="right_items">
											<?php if($furniture_material): ?>
												<div class="attribute_item">
													<span class="label"><?php echo __('Material:'); ?></span>
													<span class="value"><?php echo $furniture_material; ?></span>
												</div>
											<?php endif; ?>
											<?php if($facade_color): ?>
												<?php
													$color_ids = $_product->getFacadeColor();
													$color_ids_array = explode(',', $color_ids);
													$swatchCollection = $om->create('Amasty\Shopby\Model\ResourceModel\OptionSetting\Collection');
													$swatchCollection->addFieldtoFilter('value',$color_ids_array);
												?>
												<?php if(count($swatchCollection) > 0): ?>
													<div class="attribute_item">
														<span class="label"><?php echo __('Color:'); ?></span>
														<span class="value">
															<?php foreach($swatchCollection as $swatch_item): ?>
																<?php if($swatch_item->getImage()): ?>
																	<?php
																		$mediaPath = $om->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
																	?>
																	<img src="<?php echo $mediaPath.'amasty/shopby/option_images/'.$swatch_item->getImage(); ?>" alt="<?php $swatch_item->getTitle() ?>"/>
																<?php endif; ?>
															<?php endforeach; ?>
														</span>
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
									<?= $block->getProductDetailsHtml($_product) ?>
								</div>
								<div class="right_column">
									<div class="product-item-inner">
										<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
											<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
												<?php if ($_product->isSaleable()): ?>
													<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="action tocart primary">
														<span><?= /* @escapeNotVerified */ __('Buy') ?></span>
													</a>
													<?php /* $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $postParams['action'] ?>" method="post">
														<input type="hidden" name="product" value="<?php echo $postParams['data']['product'] ?>">
														<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
														<?= $block->getBlockHtml('formkey') ?>
														<button type="submit"
																title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
																class="action tocart primary">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													</form><?php  */ ?>
												<?php else: ?>
													<?php if ($_product->isAvailable()): ?>
														<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										</div>
									</div>
									
									<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
		</div>
	<?php endif; ?>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
