<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Tigren\Ajaxlogin\Block\Form\Register
 */
?>
<div class="mb-register-popup" style="display:none;">
    <div class="white_block block">
        <a  class="mb-ajaxsuite-close-custome mb-ajaxsuite-close"></a>
        <div class="mb-login-popup-title">
            <span class="mb-login-popup-title-logo">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <strong><?php echo __('Registration'); ?></strong>
        </div>
        <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-register">
            <form class="form form-create-account mb-login-form-register"
                  method="post"
                  id="register-form"
                  enctype="multipart/form-data" autocomplete="off">
                <fieldset class="fieldset create info">
                    <legend class="legend"><span><?php echo __('Personal Information') ?></span></legend>
                    <br>
                    <input type="hidden" name="success_url" value="">
                    <input type="hidden" name="error_url" value="">
                    <div class="field field-name-firstname required">
                        <label class="label" for="firstname">
                            <span><?php echo __('First Name') ?></span>
                        </label>
                        <div class="control">
                            <input type="text" id="firstname" name="firstname" value="" title="First Name"
                                   class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                                   aria-required="true" placeholder="<?php echo __('First Name') ?>*">
                        </div>
                    </div>
                    <div class="field field-name-lastname required">
                        <label class="label" for="lastname">
                            <span><?php echo __('Last Name') ?></span>
                        </label>

                        <div class="control">
                            <input type="text" id="lastname" name="lastname" value="" title="Last Name"
                                   class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                                   aria-required="true" placeholder="<?php echo __('Last Name') ?>*">
                        </div>
                    </div>
                    <div class="field required">
                        <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
                        <div class="control">
                            <input type="email" name="email" autocomplete="email" id="email_address" value="" title="Email"
                                   class="input-text" data-validate="{required:true, 'validate-email':true}"
                                   aria-required="true" placeholder="<?php echo __('Email') ?>*">
                        </div>
                    </div>

                    <div class="field choice newsletter">
                        <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1"
                               id="is_subscribed" class="checkbox">
                        <label for="is_subscribed" class="label"><span><?php echo __('Sign Up for Newsletter') ?></span></label>
                    </div>

                </fieldset>
                <fieldset class="fieldset create account password " data-hasrequired="* Required Fields">
                    <legend class="legend"><span><?php echo __('Sign-in Information') ?></span></legend>
                    <br>

                    <div class="field password required">
                        <label for="password" class="label"><span><?php echo __('Password') ?></span></label>
                        <div class="control">
                            <input type="password" name="password" id="password" title="Password" class="input-text"
                                   data-password-min-length="4" data-password-min-character-sets="1"
                                   data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                                   aria-required="true" placeholder="<?php echo __('Password') ?>*">
                        </div>

                    </div>
                    <div class="field confirmation required">
                        <label for="password-confirmation" class="label"><span><?php echo __('Confirm Password') ?></span></label>
                        <div class="control">
                            <input type="password" name="password_confirmation" title="Confirm Password"
                                   id="password-confirmation" class="input-text"
                                   data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                                   aria-required="true" placeholder="<?php echo __('Confirm Password') ?>*">
                        </div>
                    </div>
                    <div class="field choice consent required">
                        <input type="checkbox" name="consent" title="Consent" value=""
                               id="consent" class="checkbox required-entry" data-validate='{"required":true}'>
                        <label for="consent" class="label"><span><?php echo __('I consent to the processing of my personal data') ?></span></label>
                        <div id="required_consent" class="required_consent" style="display: none"><?php echo __('This is a required field.') ?></div>
                    </div>
                </fieldset>
                <div class="clr"></div>
                <div class="actions mb-style-actions">
                    <div class="primary">
                        <button type="submit" class="action submit primary"
                                title="Create Account"><span><?php echo __('Sign up') ?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="green_block block">
        <div class="actions">
            <span class="title"><?php echo __('Login'); ?></span>
            <span class="block_info_text"><?php echo __('If you are a registered user'); ?></span>
            <div class="secondary">
                <a class="action back button" href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <span class="mb-back-link"><?php echo __('Login') ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    require(['jquery'],function($) {
        $(document).ready(function () {
            var consent = $('#consent');
            $('button[title="Create Account"]').on('click',function () {
                if (consent.is(':checked')) {
                    $('#required_consent').hide();
                } else {
                    $('#required_consent').show();
                    return false;
                }
            });
        });
    });
</script>